name: Terraform PR
on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
        terraform_wrapper: true

    - name: Terraform Version
      run: terraform version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::916740064153:role/OlistflowGithubRole
        aws-region: us-east-1

    - name: Fix OIDC for Terraform Backend
      run: |
        echo "AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token" >> $GITHUB_ENV
        echo $AWS_WEB_IDENTITY_TOKEN_FILE | cat > $(pwd)/web-identity-token  # Pipe token
      env:
        AWS_WEB_IDENTITY_TOKEN_FILE: ${{ env.AWS_WEB_IDENTITY_TOKEN_FILE }}

    - name: Terraform Init
      run: terraform init -input=false
      working-directory: ./infra

    - name: Terraform Format
      run: terraform fmt -check || true  # Continue on fail
      working-directory: ./infra

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./infra

    - name: Terraform Plan
      id: plan
      continue-on-error: true
      run: terraform plan -no-color -input=false -detailed-exitcode
      working-directory: ./infra
      
    - uses: actions/github-script@v7
      env:
        PLAN: ${{ steps.plan.outputs.stdout }}
        PLAN_ERR: ${{ steps.plan.outputs.stderr }}
        PLAN_EXIT: ${{ steps.plan.outputs.exitcode }}
      with:
        script: |
          const plan = (process.env.PLAN ?? '') + (process.env.PLAN_ERR ? `\n${process.env.PLAN_ERR}` : '');
          const output = `#### Terraform Plan 📖 (exit ${process.env.PLAN_EXIT})\n\`\`\`hcl\n${plan}\n\`\`\``;

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          });

