name: Terraform Apply
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write  # For OIDC

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::916740064153:role/OlistflowGithubRole
        aws-region: us-east-1 
        
    - name: Terraform Init
      run: terraform init
      working-directory: ./infra
      
    - name: Terraform Plan
      run: terraform plan -no-color
      working-directory: ./infra
      
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./infra
